'use client';
import store from "@/store/store";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <head>
          <script src="https://cdn.tailwindcss.com"></script>
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>

  );
}
